### ISSUE TITLE
Related work: Comby

### ISSUE THREAD

**Issue by aryx** [jgke/syntax-searcher#1]
This seems quite related to comby: https://comby.dev/
Could you explain what are the pro/cons of syntax-searcher vs comby?

**Comment by jgke** [comment]
Thanks for the link, I couldn't find that one when I was searching for existing solutions :)

From a quick look, comby looks like a really similar tool built using similar principles. It looks like comby is more developed with replacing code in mind, while syns is developed with searching in mind -- of course, the two targets are pretty close together. Also, I'd guess comby is somewhat more mature since it has had more than one pair of eyes looking at it. Maybe syns could be compared to grep and comby to sed?

**Comment by aryx** [comment]
yep, maybe the focus of comby is indeed more sed.
